### ISSUE TITLE
Support for Yakuake

### ISSUE THREAD

**Issue by naraesk** [I-Dream-in-Code/kde-arch-update-plasmoid#17]
This is a feature request. :-)

I have yakuake running all the time. Would be nice if the kde-arch-update-plasmoid would be able to fetch the running yakuake instance and execute the commands with this instance.

**Comment by I-Dream-in-Code** [comment]
Seems like a lot of work for a single user feature.

I'm happy to explain my code to you (it's commented really well) if you feel like submitting a patch

**Comment by I-Dream-in-Code** [comment]
There's no documentation for yakuake so I can't figure out yakuake scripting.

If you know yakuake scripting I'd be happy to merge your patch

**Comment by naraesk** [comment]
Thanks for your response. From my point of view, the easiest way is to use qdbus to interact with yakuake. The following shell script checks if yakuake is running, starts a new session and runs a predefined command:

```#!/bin/bash
RUNNING =`ps cax | grep yakuake`
if [ -z "$RUNNING" ]; then
    /usr/bin/yakuake & > /dev/null 
    sleep 3 
fi

SESSION=$(qdbus-qt5 org.kde.yakuake /yakuake/sessions org.kde.yakuake.addSession)
qdbus-qt5 org.kde.yakuake /yakuake/tabs setTabTitle $SESSION "update"
qdbus-qt5 org.kde.yakuake /yakuake/sessions runCommandInTerminal $SESSION "sudo pacman -Syu"
```
I know, that's not really a patch. But that should be all you need, shouldn't it? You just have to run the script. Might be a bit more beautiful using C++ with QProcess and QtDbus modules, but it will work.

**Comment by I-Dream-in-Code** [comment]
The command I use for upgrade in both konsole and aur is

`'sh -c "sudo pacman -Syu ; echo Update Finished'"`

can yakuake support chain commands?

**Comment by naraesk** [comment]
Sure, no problem. Yakuake is based on KonsolePart and should support everything Konsole supports.

**Comment by I-Dream-in-Code** [comment]
I'll look into it.

**Comment by I-Dream-in-Code** [comment]
So I don't understand dbus well enough to implement this myself.

HOWEVER I did make a yukuake branch that has all the rest of the plasmoid logic filled in minus implenting the qdbus calls so you can submit the patch

it's in `worker.cpp` lines  365 and 290

**Comment by naraesk** [comment]
Thanks, I'll have a look at it on the weekend

**Comment by I-Dream-in-Code** [comment]
thanks for coding it

bc5c5781d1ab6ff01451ca227da3aac594897be0 is the master merge

**Comment by I-Dream-in-Code** [comment]
@naraesk when I run either command it parses it correctly but when yakuake runs it asks for sudo password then immediately quits and runs update finished

It passes over the sudo prompt and doesn't wait for a password.

Is this a configuration on my end? or do I need to change the code?

**Comment by naraesk** [comment]
Sorry, it's my bad. I configured my system a while ago so to use pacman without asking for a password, that's why it was working for me. But i can fix it

**Comment by I-Dream-in-Code** [comment]
@naraesk 

0303868d2e1fc12f08c256f30ae19e8c3e8cd0ff fixed the intialization and plugged the memory leak resulting in it

you need to fix the actual call so it waits to accept sudo password

**Comment by naraesk** [comment]
If yakuake is already running, your changes lead to an infinite loop since this -> yakuakeProcess will always be NULL.

**Comment by I-Dream-in-Code** [comment]
You're right.

I fixed it but I still feel like there's a memory leak maybe?

If someone quits yakuake when it's started from the plasmoid then the `Qprocess yakuakeProcess` pointer isn't freed the process is just destroyed and you make `new` again.

I can check if PID<=0 to free it

**Comment by I-Dream-in-Code** [comment]
so I realized there's `deleteLater()` function that cleans up the memory for me

anyways the infinite loop is fixed now along with the memory leak

**Comment by I-Dream-in-Code** [comment]
@naraesk  I just need you to fix the actual asking for sudo password issue now

**Comment by I-Dream-in-Code** [comment]
My only guess (though I can't figure out the commands even with intensive websearching) is that when it runs the window isn't visible and so it's ignoring the password prompt.

So if the window was visible then maybe it'd work?

**Comment by fancytenseletters** [comment]
After recent updates clicking on "Update System" does nothing on my machine. Downgrading to `3.5.4-1` fixes this. Can we revert all latest changes instead of commenting them out?

**Comment by I-Dream-in-Code** [comment]
@fancytenseletters  i reverted it and added pkgver() function with tags

**Comment by I-Dream-in-Code** [comment]
@naraesk I merged with master thanks for fixing it
@fancytenseletters I reverted but then fixed yakuake

AUR package and master are both updated

**Comment by fancytenseletters** [comment]
@I-Dream-in-Code it still doesn't work for me. "Update system" doesn't execute any command. Also there is no option to check yakuake in options (have it installed but don't want to use it anyway).

**Comment by I-Dream-in-Code** [comment]
@fancytenseletters sorry that merge failed

it's updated now

**Comment by fancytenseletters** [comment]
It works now! Thx.
